import { DEFAULT_BLOG_CONFIG } from "@/constants/default-blog-config";
import { CONFIG_FILENAME, REPO_NAME } from "@/constants/github";
import { Octokit } from "octokit";
import yaml from "js-yaml";

export async function createDefaultConfig(
  accessToken: string,
  username: string,
): Promise<{ success: boolean }> {
  const octokit = new Octokit({ auth: accessToken });

  const yamlContent = yaml.dump(DEFAULT_BLOG_CONFIG, {
    indent: 2,
    lineWidth: -1,
  });

  const fileContent = `# Blog Styling Configuration\n# This file controls the appearance of your blog posts\n# Edit these values to customize colors, fonts, and spacing\n\n${yamlContent}`;

  await octokit.rest.repos.createOrUpdateFileContents({
    owner: username,
    repo: REPO_NAME,
    path: CONFIG_FILENAME,
    message:
      "[auto] config: add default blog config\n\nAutomatically generated by RepoBlog application.",
    content: Buffer.from(fileContent).toString("base64"),
  });

  return { success: true };
}
