import { CONFIG_FILENAME, REPO_NAME } from "@/constants/github";
import type { BlogConfig } from "@/types/blog";
import { DEFAULT_BLOG_CONFIG } from "@/constants/default-blog-config";
import yaml from "js-yaml";
import { fetchWithRetry } from "./fetch-retry";
import { env } from "@/env";
import { Octokit } from "octokit";

export async function createDefaultConfig(
  accessToken: string,
): Promise<{ success: boolean }> {
  const octokit = new Octokit({ auth: accessToken });
  const repoData = await octokit.rest.repos.get({
    owner: env.OWNER_GITHUB_USERNAME,
    repo: REPO_NAME,
  });

  const defaultBranch = repoData.data.default_branch;
  const yamlContent = yaml.dump(DEFAULT_BLOG_CONFIG, {
    indent: 2,
    lineWidth: -1,
  });

  const fileContent = `# Blog Styling Configuration\n# This file controls the appearance of your blog posts\n# Edit these values to customize colors, fonts, and spacing\n\n${yamlContent}`;

  await octokit.rest.repos.createOrUpdateFileContents({
    owner: env.OWNER_GITHUB_USERNAME,
    repo: REPO_NAME,
    path: CONFIG_FILENAME,
    message:
      "[auto] config: add default blog config\n\nAutomatically generated by RepoBlog application.",
    content: Buffer.from(fileContent).toString("base64"),
    branch: defaultBranch,
  });

  return { success: true };
}

export async function getBlogConfig(): Promise<BlogConfig> {
  const token = env.GITHUB_TOKEN;
  const owner = env.OWNER_GITHUB_USERNAME;

  if (!token || !owner) {
    console.warn("Missing GitHub credentials, using default config");
    return DEFAULT_BLOG_CONFIG;
  }

  try {
    // get repository info to find default branch
    const repoResponse = await fetchWithRetry(() =>
      fetch(`https://api.github.com/repos/${owner}/${REPO_NAME}`, {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github+json",
        },
        next: { revalidate: 0 },
      }),
    );

    if (!repoResponse.ok) {
      console.warn("Failed to fetch repo info, using default config");
      return DEFAULT_BLOG_CONFIG;
    }

    const repoData = await repoResponse.json();
    const defaultBranch = repoData.default_branch;

    // fetch config from root of repo
    const configResponse = await fetchWithRetry(() =>
      fetch(
        `https://api.github.com/repos/${owner}/${REPO_NAME}/contents/${CONFIG_FILENAME}?ref=${defaultBranch}`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github+json",
          },
          next: { revalidate: 0 },
        },
      ),
    );

    if (!configResponse.ok) {
      console.warn(`${CONFIG_FILENAME} not found, using default config`);
      return DEFAULT_BLOG_CONFIG;
    }

    const configData = await configResponse.json();
    const yamlContent = Buffer.from(configData.content, "base64").toString(
      "utf-8",
    );

    const config = yaml.load(yamlContent) as BlogConfig;
    return config;
  } catch (error) {
    console.error("Error fetching blog config:", error);
    return DEFAULT_BLOG_CONFIG;
  }
}
