import { CONFIG_FILENAME, REPO_NAME } from "@/constants/github";
import { ENV } from "@/env";
import type { BlogConfig } from "@/types/blog";
import { DEFAULT_BLOG_CONFIG } from "@/constants/default-blog-config";
import yaml from "js-yaml";
import { fetchWithRetry } from "./fetch-retry";

export async function createDefaultConfigInRepo(
  accessToken: string,
): Promise<{ success: boolean; error?: string }> {
  const owner = ENV.OWNER_GITHUB_USERNAME;

  if (!owner) {
    return { success: false, error: "Missing OWNER_GITHUB_USERNAME" };
  }

  try {
    // get default branch
    const repoResponse = await fetch(
      `https://api.github.com/repos/${owner}/${REPO_NAME}`,
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          Accept: "application/vnd.github+json",
        },
      },
    );

    if (!repoResponse.ok) {
      return { success: false, error: "Failed to fetch repository info" };
    }

    const repoData = await repoResponse.json();
    const defaultBranch = repoData.default_branch;

    // convert default config to YAML
    const yamlContent = yaml.dump(DEFAULT_BLOG_CONFIG, {
      indent: 2,
      lineWidth: -1,
    });

    // add header comment
    const fileContent = `# Blog Styling Configuration
# This file controls the appearance of your blog posts
# Edit these values to customize colors, fonts, and spacing

${yamlContent}`;

    // create file in repo
    const createResponse = await fetch(
      `https://api.github.com/repos/${owner}/${REPO_NAME}/contents/${CONFIG_FILENAME}`,
      {
        method: "PUT",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          Accept: "application/vnd.github+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message:
            "[auto] config: add default blog config\n\nAutomatically generated by RepoBlog application.",
          content: Buffer.from(fileContent).toString("base64"),
          branch: defaultBranch,
        }),
      },
    );

    if (!createResponse.ok) {
      const error = await createResponse.text();
      return { success: false, error: `Failed to create config: ${error}` };
    }

    return { success: true };
  } catch (error) {
    console.error("Error creating config in repo:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

export async function getBlogConfig(): Promise<BlogConfig> {
  const token = ENV.GITHUB_TOKEN;
  const owner = ENV.OWNER_GITHUB_USERNAME;

  if (!token || !owner) {
    console.warn("Missing GitHub credentials, using default config");
    return DEFAULT_BLOG_CONFIG;
  }

  try {
    // get repository info to find default branch
    const repoResponse = await fetchWithRetry(() =>
      fetch(`https://api.github.com/repos/${owner}/${REPO_NAME}`, {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github+json",
        },
        next: { revalidate: 0 },
      }),
    );

    if (!repoResponse.ok) {
      console.warn("Failed to fetch repo info, using default config");
      return DEFAULT_BLOG_CONFIG;
    }

    const repoData = await repoResponse.json();
    const defaultBranch = repoData.default_branch;

    // fetch config from root of repo
    const configResponse = await fetchWithRetry(() =>
      fetch(
        `https://api.github.com/repos/${owner}/${REPO_NAME}/contents/${CONFIG_FILENAME}?ref=${defaultBranch}`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github+json",
          },
          next: { revalidate: 0 },
        },
      ),
    );

    if (!configResponse.ok) {
      console.warn(`${CONFIG_FILENAME} not found, using default config`);
      return DEFAULT_BLOG_CONFIG;
    }

    const configData = await configResponse.json();
    const yamlContent = Buffer.from(configData.content, "base64").toString(
      "utf-8",
    );

    const config = yaml.load(yamlContent) as BlogConfig;
    return config;
  } catch (error) {
    console.error("Error fetching blog config:", error);
    return DEFAULT_BLOG_CONFIG;
  }
}
